# Developed by: Eng. Mouaz M. AlShahmeh
name: solitaire_flutter_game
description: Developed by Eng Mouaz M AlShahmeh
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Domine
      fonts:
        - asset: fonts/Domine-Regular.ttf
